groups:
- name: Alerta sobre média dos máximos
  rules:

  # Rate of requests per second
  - record: http_requests_seconds_summary_count:sum_irate1m
    expr:
      sum(
        irate(http_requests_seconds_summary_count[1m])
      ) by (uri, status)

  # Average over time (1m) to make data smoother
  - record: http_requests_seconds_summary_count:avg1m_sum_irate1m
    expr: avg_over_time( http_requests_seconds_summary_count:sum_irate1m[1m] )

  # Predict rate of requests in 10m based on smoothed data
  - record: http_requests_seconds_summary_count:predict15m_avg1m_sum_irate1m
    expr: predict_linear( http_requests_seconds_summary_count:avg1m_sum_irate1m[15m], 600 ) > 0

  # Record max rate of requests over 1h based on smoothed data
  - record: http_requests_seconds_summary_count:max1h_avg1m_sum_irate1m
    expr: max_over_time( http_requests_seconds_summary_count:avg1m_sum_irate1m[1h] )

  # Average over time (3h) of peaks (max) rate of requests to use on alert
  - record: http_requests_seconds_summary_count:avg3h_max1h_avg1m_sum_irate1m
    expr: avg_over_time( http_requests_seconds_summary_count:max1h_avg1m_sum_irate1m[3h] )

  # If rate of requests per second is greater than the average of peaks
  - alert: http_requests_seconds_summary_count_abnormal_increase
    expr:
      http_requests_seconds_summary_count:predict15m_avg1m_sum_irate1m
      >
      http_requests_seconds_summary_count:avg3h_max1h_avg1m_sum_irate1m
    for: 10m
    annotations:
      description: Taxa de crescimento anormal da frequência de requisições por segundo, indicando quebra de recorde histórico. Versão do Centralizador '{{ $labels.component_version }}', Status '{{ $labels.status }}', Versão App '{{ $labels.device_app_version }}'.
      summary: Caso a predição sobre a média da frequência de requisições http do aplicativo supere a média dos picos durante dez minutos, um alerta será lançado.
